### PR TITLE
New changes

### PR DESCRIPTION
**Pull request by LoliJuicy**
I posted a few screenshots to you showing the new restructuring of the objective goals and I cleaned up the script a bit.

Here's what new:

* Removed the goal "habitat set up" and condensed into two sub-goals of "huge biome overall": Quota and Counter

* Replaced the Zoo System Message used for the message with a Generic "OK" Panel Message.

* Reorganized the script to follow up with the changes

* The "Counter" goal is hidden. To reveal, the "Quota" goal must be met.

* If either the carnivore or herbivore do not meet the initial quota in the same exhibit, the "Counter" goal will be hidden and the "Quota" goal will be set to neutral.

* In following up with the above changes, a new set of strings have been created for the sub-goals. Dutch has yet to be updated!

What's not fixed:

* Ibexes' Behaviour

* A few grasses that sits on the asphalt path

* Not part of it but Ibexes are not able to access one of the trough because a tree is blocking. I might shift it to a more open area.

Bugs:

* If you make any modifications to the exhibit (e.g. making the area bigger/smaller, painting biome, or adding medium/large rocks), the "herbivoresInCarnivoresHabitat" value gets reset and the counter gets reset as well. See if the function "inSameHabitat" is the root problem.

### CODE REVIEW

**Review by Zt-freak — CHANGES_REQUESTED** [review]
Please fix the merge conflicts

**Review by LoliJuicy — COMMENTED** [review]
The way GitHub checks is so weird. A .zt2 file should be ignored but it is able to find an error when it should be unreadable? Kind of annoying. Going to Desktop ver.

**Comment by LoliJuicy** [comment]
Problems of Conflicts:

1. README.md 
2. worldcampscen4.zt2 presumably because of the file size
3. Habitatsetup is removed from worldcampaignscen4.xml and replaced with Quota and Counter sub-goals
4. worldcampaign_new.lua has been renamed to CompleteEcosystem.lua

**Comment by LoliJuicy** [comment]
> Please fix the merge conflicts

Resolved merge conflicts.

**Review by Zt-freak — APPROVED** [review]

**Pull request merged**
